export const countryToISO3 = {
    "Montenegro": "MNE",
    "North Macedonia": "MKD",
    "State of Palestine": "PSE",
    "Palestine": "PSE", // alternate
    "Albania": "ALB",
    "Niger": "NER",
    "Myanmar": "MMR",
    "Viet Nam": "VNM", // alternate
    "Iran": "IRN",
    "Liberia": "LBR",
    "Burkina Faso": "BFA",
    "Gabon": "GAB",
    "Cameroon": "CMR",
    "Azerbaijan": "AZE",
    "Madagascar": "MDG",
    "Cambodia": "KHM",
    "Laos": "LAO",
    "Lao PDR": "LAO", // alternate
    "Senegal": "SEN",
    "Gambia": "GMB",
    "Morocco": "MAR",
    "Namibia": "NAM",
    "Ukraine": "UKR",
    "Mali": "MLI",
    "Benin": "BEN",
    "Tunisia": "TUN",
    "Kenya": "KEN",
    "Bangladesh": "BGD",
    "India": "IND",
    "Pakistan": "PAK",
    "Jordan": "JOR",
    "Egypt": "EGY",
    "Ghana": "GHA",
    "Tanzania": "TZA",
    "Togo": "TGO",
    "Sri Lanka": "LKA",
    "Yemen": "YEM",
    "Nigeria": "NGA",
    "Ethiopia": "ETH",
    "Malawi": "MWI",
    "Sierra Leone": "SLE",
    "Uganda": "UGA",
    "Comoros": "COM",
    "Eswatini": "SWZ",
    "Swaziland": "SWZ", // alternate
    "Zimbabwe": "ZWE",
    "Lesotho": "LSO",
    "Congo (Kinshasa)": "COD",
    "DR Congo": "COD", // alternate
    "Congo": "COG",
    "Congo (Brazzaville)": "COG",
    "Botswana": "BWA",
    "Lebanon": "LBN",
    "Zambia": "ZMB",
    "Afghanistan": "AFG",
    "Guatemala": "GTM",
    "Libya": "LBY",
    "Latvia": "LVA",
    "El Salvador": "SLV",
    "Mongolia": "MNG",
    "Serbia": "SRB",
    "Kyrgyzstan": "KGZ",
    "Panama": "PAN",
    "Cyprus": "CYP",
    "North Cyprus": "XNC", // alternate
    "Honduras": "HND",
    "South Korea": "KOR",
    "Republic of Korea": "KOR", // alternate
    "Slovakia": "SVK",
    "Bahrain": "BHR",
    "Algeria": "DZA",
    "Portugal": "PRT",
    "Venezuela": "VEN",
    "Bolivia": "BOL",
    "Russia": "RUS",
    "Russian Federation": "RUS", // alternate
    "Greece": "GRC",
    "Jamaica": "JAM",
    "Vietnam": "VNM",
    "Hungary": "HUN",
    "Malaysia": "MYS",
    "Colombia": "COL",
    "Peru": "PER",
    "Hong Kong SAR of China": "HKG",
    "Hong Kong": "HKG", // alternate
    "Dominican Republic": "DOM",
    "Dominican Rep.": "DOM", // alternate
    "Nepal": "NPL",
    "Bosnia and Herzegovina": "BIH",
    "Bosnia and Herz.": "BIH", // alternate
    "Indonesia": "IDN",
    "Croatia": "HRV",
    "Guinea": "GIN",
    "South Africa": "ZAF",
    "Paraguay": "PRY",
    "Ecuador": "ECU",
    "Moldova": "MDA",
    "Republic of Moldova": "MDA", // alternate
    "Tajikistan": "TJK",
    "Armenia": "ARM",
    "Mozambique": "MOZ",
    "Bulgaria": "BGR",
    "Georgia": "GEO",
    "Turkey (Türkiye)": "TUR",
    "Turkey": "TUR", // alternate
    "Mauritania": "MRT",
    "Chad": "TCD",
    "Iraq": "IRQ",
    "Ivory Coast": "CIV",
    "Côte d’Ivoire": "CIV", // alternate
    "Denmark": "DNK",
    "Finland": "FIN",
    "Norway": "NOR",
    "Sweden": "SWE",
    "Iceland": "ISL",
    "New Zealand": "NZL",
    "Netherlands": "NLD",
    "Canada": "CAN",
    "Australia": "AUS",
    "United States": "USA",
    "United Arab Emirates": "ARE",
    "Luxembourg": "LUX",
    "Kuwait": "KWT",
    "Switzerland": "CHE",
    "Austria": "AUT",
    "Ireland": "IRL",
    "Costa Rica": "CRI",
    "Israel": "ISR",
    "Belgium": "BEL",
    "United Kingdom": "GBR",
    "Germany": "DEU",
    "Uzbekistan": "UZB",
    "Czechia": "CZE",
    "Czech Rep.": "CZE", // alternate
    "Uruguay": "URY",
    "France": "FRA",
    "Singapore": "SGP",
    "Saudi Arabia": "SAU",
    "Mauritius": "MUS",
    "Malta": "MLT",
    "Spain": "ESP",
    "China": "CHN",
    "Taiwan Province of China": "TWN",
    "Taiwan": "TWN", // alternate
    "Estonia": "EST",
    "Japan": "JPN",
    "Brazil": "BRA",
    "Italy": "ITA",
    "Kosovo": "XKX",
    "Poland": "POL",
    "Thailand": "THA",
    "Kazakhstan": "KAZ",
    "Philippines": "PHL",
    "Lithuania": "LTU",
    "Argentina": "ARG",
    "Chile": "CHL",
    "Nicaragua": "NIC",
    "Romania": "ROU",
    "Angola": "AGO",
    "Belarus": "BLR",
    "Belize": "BLZ",
    "Bhutan": "BTN",
    "Burundi": "BDI",
    "Central African Republic": "CAF",
    "Cuba": "CUB",
    "Djibouti": "DJI",
    "Oman": "OMN",
    "Guyana": "GUY",
    "Haiti": "HTI",
    "Trinidad and Tobago": "TTO",
    "Puerto Rico": "PRI",
    "Rwanda": "RWA",
    "Somalia": "SOM",
    "Somaliland Region": "SOM", // alternate
    "South Sudan": "SSD",
    "Sudan": "SDN",
    "Suriname": "SUR",
    "Syria": "SYR",
    "Turkmenistan": "TKM",
    "Falkland Is.": "FLK",
    "Greenland": "GRL",
    "Brunei": "BRN",
    "Timor-Leste": "TLS",
    "Fiji": "FJI",
    "New Caledonia": "NCL",
    "Papua New Guinea": "PNG",
    "Solomon Is.": "SLB",
    "Vanuatu": "VUT",
    "Bahamas": "BHS",
    "Mexico": "MEX",
    "N. Cyprus": "XNC",           // alternate for North Cyprus
    "Korea": "KOR",               // alternate for South Korea
    "Dem. Rep. Korea": "PRK",     // North Korea
    "Qatar": "QAT",
    "Côte d'Ivoire": "CIV",
    "Central African Rep.": "CAF",
    "Dem. Rep. Congo": "COD",
    "Eritrea": "ERI",
    "Guinea-Bissau": "GNB",
    "Eq. Guinea": "GNQ",
    "W. Sahara": "ESH",
    "S. Sudan": "SSD",
    "Somaliland": "SOM",
    "Macedonia": "MKD",
    "Slovenia": "SVN",
    "Maldives": "MDV",
    "Türkiye": "TUR",
};
